on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: string

jobs:
  screenshots_check:
    name: Run Roborazzi testing
    runs-on: ubuntu-20.04
    steps:
      - name: Run all local screenshot tests (Roborazzi)
        id: screenshotsverify
        continue-on-error: true
        run: ./gradlew verifyRoborazziDebug

      - name: Process failed screenshot tests
        if: steps.screenshotsverify.outcome == 'failure'
        id: failed-screenshots
        run: "./.github/scripts/update_screenshots.sh"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          PULL_REQUEST_BRANCH: ${{ github.head_ref }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ inputs.pull_request_number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Roborazzi report'

      - name: Report Roborazzi success
        if: steps.screenshotsverify.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### ðŸ¤– Roborazzi report
            âœ… **Screenshot Tests Passed**
          edit-mode: replace

      - name: Report Roborazzi failure
        if: steps.screenshotsverify.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### ðŸ¤– Roborazzi report
            ðŸš¨ **Screenshot Tests Failed**
            ***
            [See differences](${{ steps.failed-screenshots.outputs.PULL_REQUEST_URL }})
            Merge the branch if it's an intentional change. Otherwise fix UI and push new changes in current branch
          edit-mode: replace

      # Runs only if previous steps failed
      - name: Fail Job Explicitly if Tests Failed
        if: steps.screenshotsverify.outcome == 'failure'
        run: exit 1